### ISSUE TITLE
Wrong directory when `dir` is not defined

### ISSUE THREAD

**Issue by Louson** [cpb-/yocto-cooker#132]
If I use the layer:

 ```
   {
      "url": "git://git@github.com:rauc/meta-rauc",
      "branch": "kirkstone",
      "rev": "3796f982df039451f813ec979c431676965263f9"
    }
```

The directory in bblayers.conf is : 
`${TOPDIR}/../../layers/meta-rauc \`

but the update command stores it in : 
`layers/rauc/meta-rauc.git`

**Comment by pboettch** [comment]
I'm sure you have, but did you call generate to update bblayers?

**Comment by Louson** [comment]
Sorry, I made a stupid confusion, I should have triple checked. I was a bit disturbed that the ".git" remains in the path.
