### ISSUE TITLE
[RFC] How about `dumpenv` command?

### ISSUE THREAD

**Issue by cpb-** [cpb-/yocto-cooker#152]
I would be interested in a `cooker dumpenv [build]` command.

Instead of running `bitbake <image-name>` it would run `bitbake -e <image-name>` and redirect the standard output to a `environment.txt` file located in the build directory.

It would be useful to see the content of some quite complex variables (`*OVERRIDES` or `*_FEATURES` for example) after `bitbake` parsing of the recipes.

Any comment?

**Comment by boucman** [comment]
hmm

bitbake -e has multiple variants, all of which are usefull

bitbake -e
bitbake -e <image>
bitbake -e <any recipe>

how would you proposal work for that ?

**Comment by cpb-** [comment]
🤨

**Comment by pboettch** [comment]
what about `cooker shell <target> bitbake -e` ?

**Comment by cpb-** [comment]
```
$ cooker shell raspberrypi4   bitbake -e
usage: cooker [-h] [--debug] [--version] [-v] [-n]
              {cook,init,update,diff,log,generate,show,build,shell,clean} ...
cooker: error: unrecognized arguments: -e

$ cooker shell raspberrypi4   "bitbake -e"
/bin/bash: line 1: bitbake -e: command not found
```

**Comment by pboettch** [comment]
Doesn't work, but would this be an acceptable solution?

**Comment by cpb-** [comment]
Never mind, I've done it another way.
