### ISSUE TITLE
Easy way to setup a yocto shell

### ISSUE THREAD

**Issue by boucman** [cpb-/yocto-cooker#76]
The yocto shell (i.e after oe-init-build-env) provides all sorts of commands and shortcuts.
Once the initial setup has been done with cooker it would be usefull to be able to set up the environment easily.

I am not sure how to do that
* better advertise the command
* add a shell-script to source at the root of the cooker directory
* add a "cooker shell" subcommand
But having to find where the oe-init-build-env and build-dir manually is a bit against the cooker logic of hiding that kind of stuff..

Cheers
Jeremy

**Comment by pboettch** [comment]
Would an interactive shell like as if you run `. oe-init-build-env` manually be sufficient?

If so, you can enable a verbose mode by running `cooker show <build-name` and if will print a line which is correct relative to the path where you are:

```bash
$ cd cooker-based-project/build 
$ ls ..
builds  layers  sstate-cache
$ cooker show -b railnet-minimal
# build: railnet-minimal (bakes railnet-minimal-bundle)
#   . ../layers/poky/oe-init-build-env build-railnet-minimal
```

To enter you'd just copy the sourcing-line.

Running an interactive shell from cooker would be possible as well.

**Comment by boucman** [comment]
Thx, that's a nice trick to find out the correct line, but I think it's really a good idea to have cooker do that for you...

It's not so much that I can't find where it is, more that it's one of the first thing I need to do after deploying cooker and a thing I need to do whenever I work on a cooker based project.

It would be consistent with the other things cooker do to have a quick way to set up a yocto env using cooker to find where all the stuff is...

**Comment by pboettch** [comment]
so like `cooker shell <build-name>` ?

**Comment by boucman** [comment]
yes, exactly

**Comment by boucman** [comment]
Ideally setting a couple of extra env vars like COOKER_BUILD= and COOKER_TOPLEVEL=

**Comment by pboettch** [comment]
Could you show some usage examples regarding your env-var ideas?

**Comment by boucman** [comment]
not really, it's just an idea I had while writing the comment. I don't think it's that important and it can always be added later...
i'll keep the idea around and if I need it i'll do another FR or PR

**Comment by pboettch** [comment]
OK, thanks, but the shell command could be added easily.

**Comment by boucman** [comment]
yes... I don't have the time to learn the internal of cooker right now... so I added this as a FR in case it's a 3 line change for someone that knows the code

if not, i'll have to look into it and it will take some time before I can do a FR..

**Comment by pboettch** [comment]
@boucman  if you still interested in this feature, could you try #87 and tell us whether this fulfills your needs?

**Comment by boucman** [comment]
I'll try to have a look but I don't have a setup readily available... so it might take a little time.
