### ISSUE TITLE
Incorrect use of variable CMDLINE

### ISSUE THREAD

**Issue by Louson** [cpb-/yocto-cooker#77]
In pi3-sample-menu.json, using CMDLINE += 'quiet' erase original cmdline.txt and results in a non bootable image

A correct usage seems to be :
CMDLINE_append += 'quiet'

**Comment by pboettch** [comment]
Thanks for your PR to fix this. 

Are other image-examples affected as well?

**Comment by Louson** [comment]
That's the only menu using this

**Comment by pboettch** [comment]
Thanks for looking it up for us ;-).

**Comment by pboettch** [comment]
Fix with a4a59aff6940970ead147919f2d563a6146a0b2f
