### ISSUE TITLE
Generate oe-init-build-env scripts

### ISSUE THREAD

**Issue by orzen** [cpb-/yocto-cooker#96]
Currently, `cooker` prints the command line for sourcing `oe-init-build-env` when an error occurs for debugging. Sometimes it is useful to source `oe-init-build-env` for development reasons to access `bitbake` directly or some of the other tools (e.g. `devtool`, `recipetool`, `oe-pkgdata-util`). It would be nice if `cooker` could generate pre-configured scripts or have an option to source `oe-init-build-env` each build target.

**Comment by boucman** [comment]
hasn't such a command been added in the latest version ?

**Comment by orzen** [comment]
You are correct, thank you!
